### ISSUE TITLE
C++20 deprecation of volatile

### ISSUE THREAD

**Issue by shreck-t** [scmrtos/scmrtos#10]
Привет. C++20 постучался в embedded разработку, а в нем некоторые вещи стали deprecated.
Конкретно сейчас я говорю о "deprecation of volatile" (см. например [здесь](https://blog.feabhas.com/2021/05/modern-embedded-c-deprecation-of-volatile/))

scmRTOS компилируется с многочисленными предупреждениями.
Похоже надо поправлять код.

---

Hello. C++20 made its way into embedded development and made some things deprecated.
Specifically, now I’m talking about "deprecated of volatile" (see, for example, [here](https://blog.feabhas.com/2021/05/modern-embedded-c-deprecation-of-volatile/))

scmRTOS compiles with numerous warnings. 
Looks like the code needs to be fixed.

**Comment by antongus** [comment]
Вот же им делать больше нечего, этим стандартизаторам! :-)

Ладно scmRTOS, поправим, там кода немного. А что делать с библиотеками периферии от производителя? Там же volatile на volatile 
сидит, и volatile погоняет.

Но вообще конечно нам пора бы обновить scmRTOS, уже и без этого много накопилось в develop.

Можно приурочить обновление к "совместимости с c++20".

**Comment by antongus** [comment]
Готово, коммит c92c0321a9bf0adb617b4560ccf340fd3f7cfc50 (пока в develop). Заодно удалил устаревшие классы TCbuf и TChannel.

Проверил только порт cortex/mx-gcc, остальные порты проверять негде.

**Comment by shreck-t** [comment]
Поправил recursive_mutex ext

**Comment by antongus** [comment]
У тебя появилось лишнее чтение volatile-переменной (на if()):
```
    NestCount = NestCount - 1;   // прочитали NestCount, уменьшили, записали в NestCount
    if ( 0 == NestCount )                // ещё раз прочитали NestCount
```
лучше так:

```
    size_t cnt = NestCount - 1;
    NestCount = cnt;
    if (0 == cnt)
```

**Comment by shreck-t** [comment]
Да, поправлю.
И еще момент. Оптимизировать доступ к volatile переменным можно во многих местах . Вот у меня сомнения, надо это делать или нет. Что думаешь?

**Comment by antongus** [comment]
> Оптимизировать доступ к volatile переменным можно во многих местах .

О каких местах ты говоришь? Речь про код scmRTOS? Там вроде бы всё более-менее оптимально.

Если речь в общем, то, думаю, оптимизировать нужно. Если это volatile-регистры, то даже обязательно, чтобы избежать лишнего чтения/записи, которые могут иметь побочные эффекты. Если это просто volatile-переменная, то здесь уже по месту смотреть, но обычно тоже желательно оптимизировать.  Лично я это делаю почти автоматически :-)

**Comment by antongus** [comment]
Сейчас нашёл ещё одно такое место (в `OS::TKernel::system_timer()`):

```
        if(p->Timeout > 0)
        {
            p->Timeout = p->Timeout - 1;
            if(p->Timeout == 0)
            {
                set_process_ready(p->Priority);
            }
        }
```

меняю на 

```
        timeout_t t = p->Timeout;
        if(t > 0)
        {
            p->Timeout = --t;
            if(t == 0)
            {
                set_process_ready(p->Priority);
            }
        }
```

, пересобираю тестовый проект, и вижу, что размер кода вырос на 12 байтов! Как там может быть? Ведь я сэкономил одно чтение volatile-переменной! Не понимаю...

Так что теперь и у меня сомнения, надо ли это делать :-)

**Comment by antongus** [comment]
Посмотрел дизассемблер. Во втором случае благодаря оптимизации тело цикла сократилось, и компилятор решил развернуть этот цикл. Поэтому размер подрос. Так что конкретно в этом месте оптимизация вылезла "боком".

**Comment by harryzhurov** [comment]
Может нам обсуждения в тележном чате вести? Там, имхо, поудобнее со всех
сторон будет.

пт, 5 янв. 2024 г. в 00:18, Anton Gusev ***@***.***>:

**Comment by harryzhurov** [comment]
Зато, наверное, скорость повыше стала?

пт, 5 янв. 2024 г. в 00:18, Anton Gusev ***@***.***>:

**Comment by antongus** [comment]
> Зато, наверное, скорость повыше стала?

Нет, там хуже стало. Что-то накрутил компилятор, переходов стало больше.

> Может нам обсуждения в тележном чате вести?

Там у нас Андрей не включён. @shreck-t , присоединишься?

**Comment by shreck-t** [comment]
> > Может нам обсуждения в тележном чате вести?
> 
> Там у нас Андрей не включён. @shreck-t , присоединишься?

Да, конечно. Давайте ссылку.

**Comment by harryzhurov** [comment]
scmrtos, внезапно. :)

вт, 9 янв. 2024 г., 14:03 Andrey ***@***.***>:

**Comment by harryzhurov** [comment]
вт, 9 янв. 2024 г., 20:27 Harry Zhurov ***@***.***>:

**Comment by harryzhurov** [comment]
Не смог найти в телеге shreck-t. Андрей, кинь мне в почту ***@***.***
или на элхе в личке номер телефона, который у тебя в телеге зареган,
наверное только так можно добавить. Забыл уже напрочь, как добавлял.

вт, 9 янв. 2024 г. в 21:38, Harry Zhurov ***@***.***>:

**Comment by shreck-t** [comment]
Не нашел у себя твою почту.
Поищи в телеге по нику Andrey_Chuykin

> Не смог найти в телеге shreck-t. Андрей, кинь мне в почту ***@***.*** или на элхе в личке номер телефона, который у тебя в телеге зареган, наверное только так можно добавить. Забыл уже напрочь, как добавлял. вт, 9 янв. 2024 г. в 21:38, Harry Zhurov ***@***.***>:

**Comment by antongus** [comment]
Закрываю, вроде всё нормально
