### ISSUE TITLE
STM8/SDCC support

### ISSUE THREAD

**Issue by spth** [scmrtos/scmrtos#2]
Currently the STM8 is supported via the non-free IAR compiler only. How about adding support for free SDCC?

Philipp

**Comment by antongus** [comment]
SDCC does not support c++, so it is impossible for now.

**Comment by spth** [comment]
There is the experimental [LLVM+SDCC toolchain](http://www.colecovision.eu/llvm+sdcc/), which in principle should allow compiling scmrtos via SDCC fro STM8.

Philipp

**Comment by antongus** [comment]
Thank you for the information. I'll try to find the time to test LLVM+SDCC with c++.
