### ISSUE TITLE
TChannel: некорректный конструктор

### ISSUE THREAD

**Issue by esaulenka** [scmrtos/scmrtos#3]
коллега обратил внимание, что конструктор TChannel не инициализирует ProducersProcessMap / ConsumersProcessMap.

С большой вероятностью это не "стрельнет", т.к. объект будет наверняка статическим, но... неаккуратно это.

**Comment by harryzhurov** [comment]
Неужели ещё кто-то пользуется TChannel'ом? :)

Надо будет глянуть на досуге. Спасибо за замечание. :

**Comment by harryzhurov** [comment]
Пофиксил.
