### ISSUE TITLE
cortex-mx port: stack align

### ISSUE THREAD

**Issue by esaulenka** [scmrtos/scmrtos#6]
Есть подозрение, что некорректно считается выравнивание стека на Cortex-M4F
https://github.com/scmrtos/scmrtos/blob/c71eb018b1b3f5bbb474b0cc2afaedf737515ff7/port/cortex/mx-gcc/os_target.cpp#L97-L98

Можно сделать проще:
https://github.com/scmrtos/scmrtos/blob/e22554924653103eed3e446d57cbd1c05175ace6/port/cortex/m3-iar/os_target.cpp#L61

Подробнее обсуждали на электрониксе в теме [Универсальный порт для Cortex-Mx](https://electronix.ru/forum/index.php?app=forums&module=forums&controller=topic&id=127079&page=4).

**Comment by antongus** [comment]
Упс. Совсем забыл :(
Да, можно сделать просто & 0xFFFFFFF8. Я проверял.
Сегодня же исправлю.

**Comment by antongus** [comment]
Готово, коммит fb3daa12dfe1e32e21f2d51329c4a48ddf96e8d7.

**Comment by antongus** [comment]
Закрываю. Если что-то вылезет - откроем заново.

**Comment by spe-ciellt** [comment]
Это исправление ошибки или упрощение?

**Comment by antongus** [comment]
Это исправление ошибки.
Стек выравнивался некорректно.
