### ISSUE TITLE
interrupt latency

### ISSUE THREAD

**Issue by dsula** [scmrtos/scmrtos#7]
I was wondering if you could comment a little bit about interrupt latency of scmRTOS in the documentation.
Inspecting the code I've noticed that most kernel and service functions are encapsulated in critical section, which essentially disable interrupts globally. Is it possible to achieve 0 interrupt latency through some setting choice?

**Comment by antongus** [comment]
You can provide a custom implementation of critical section. Set the define `scmRTOS_USER_DEFINED_CRITSECT_ENABLE` to 1 in `scmRTOS_CONFIG.h`, and provide your own `TCritSect` class.

**Comment by dsula** [comment]
Yes, but I assume there are still limitations. Even if I implement my own TCritSect, which never disables interrupts. I assume ISR written in such a scenario are limited on what they can do. How can I send an event or message from a high priority ISR to a working thread? Is that possible?

**Comment by antongus** [comment]
Of course in this case you can't use OS services in a high priority interrupts. To send data to working thread you can, for example, use software interrupt with lower priority: fire lower priority interrupt, and use OS services there.

**Comment by dsula** [comment]
Ok, that's a good idea. I haven't thought of that.
