### ISSUE TITLE
Using channel::write() from ISR

### ISSUE THREAD

**Issue by AlexandrShipovsky** [scmrtos/scmrtos#9]
Добрый день!
В документации на scmRTOS сказано что для передачи данный из прерывания рекомендуется использовать message::send_isr, но я заметил функцию channel::write_isr и хотел бы с её помощью отправлять данные в очередь из обработчика прерывания UART по завершению приема с помощью DMA.
К сожалению в документации не нашел информацию о функции channel::write_isr. С какими проблемами я могу столкнуться при ее использовании?

**Comment by antongus** [comment]
`channel::write()` - может поставить вызывающий процесс в ожидание (усыпить), до того момента, когда в канале появится достаточно свободного места для записи всего блока данных. После того, как управление вернулось из вызова `channel::write()`, мы можем быть уверены, что весь блок данных записан в канал.

`channel::write_isr()` вызывается из прерывания, следовательно, не может ожидать. Поэтому эта функция пишет в канал столько, сколько помещается и возвращает количество записанных элементов. Надо учитывать эту особенность (проверять возвращённое значение, и как-то обрабатывать ситуацию, когда не все данные поместились в канал).

А в остальном `channel::write_isr()` отлично работает в прерывании.

**Comment by AlexandrShipovsky** [comment]
`channel::write_isr()` действительно хорошо работает в прерывании, спасибо! Вообще scmRTOS очень выручила в проекте с ограниченными ресурсами, спасибо что поддерживаете
